# Generated by Django 4.0.2 on 2022-02-24 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('age', models.IntegerField(verbose_name=1)),
            ],
        ),
        migrations.CreateModel(
            name='Composers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('age', models.IntegerField(verbose_name=1)),
            ],
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('age', models.IntegerField(verbose_name=1)),
            ],
        ),
        migrations.CreateModel(
            name='MovieCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('ranking', models.IntegerField(verbose_name=1)),
                ('actor', models.ManyToManyField(to='api.Actors')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.moviecategories')),
                ('composers', models.ManyToManyField(to='api.Composers')),
                ('directors', models.ManyToManyField(to='api.Directors')),
            ],
        ),
    ]
